-- ============================================================================
-- குற்றியலுகர உகர மெய்விட்டோடும் rules (வேண்டு + இன் → வேண்டின், and every
-- similarly-tagged row) — systemic fix.
--
-- These rows were generated by the same நூற்பா template used for GLIDE-
-- INSERTION rules (காலை + இல் → காலைய் + இல், i.e. a letter is ADDED), but
-- this family is the opposite phenomenon: the short உ on a குற்றியலுகரம்
-- syllable (டு/று/கு/சு/து/பு/மு...) is DROPPED (மெய்விட்டு ஓடும்) before a
-- vowel-starting suffix. Applying the insertion template produced garbage
-- like "வேண்டு + இன் + இன் → வேண்டுஇன் + இன்".
--
-- Fix, per your instruction:
--   - changed_letter → NULL (nothing is "added"; a letter is REMOVED, so
--     the connector badge should be a plain dot, not text, and the
--     "புதிதாகச் சேர்க்கப்பட்ட எழுத்து" footer should not appear)
--   - step 1 shows the dropped உ struck through, split out as its own term:
--       வேண்ட் + உ̶ + இன் → வேண்ட் + இன்
--     (the strike is a Unicode combining overlay on உ itself — no popup
--     component changes needed, it renders as struck text automatically)
--   - step 2 unchanged in structure, just uses the correct elided form:
--       வேண்ட் + இன் = வேண்டின்
--
-- Scope: every row tagged with a உ-elision leaf (உ | உயிர், கு சு து பு |
-- உயிர், டு று | உயிர், மு | உயிர்) — this is "change all such occurrences"
-- as requested. The doubling leaves (நெடில்/உயிர்த்தொடர்க் குற்றியலுகரம்)
-- are a different phenomenon (ட்/ற் doubles, nothing is dropped) and are
-- NOT touched here. மெ | உ (a different, unrelated doubling rule) is also
-- untouched.
-- ============================================================================

DO $$
DECLARE
  rec RECORD;
  part1 text;
  part2 text;
  elided text;
  struck_u text := 'உ' || chr(822); -- உ + combining long stroke overlay (U+0336)
  step1_result text;
  step2_result text;
  n int := 0;
BEGIN
  FOR rec IN
    SELECT id, before_form, after_form
    FROM sandhi_rules
    WHERE mnemonic_tag IN ('உ | உயிர்', 'கு சு து பு | உயிர்', 'டு று | உயிர்', 'மு | உயிர்')
  LOOP
    part1 := trim(split_part(rec.before_form, ' + ', 1));
    part2 := trim(split_part(rec.before_form, ' + ', 2));

    IF right(part1, 1) = 'உ' THEN
      elided := left(part1, length(part1) - 1);
    ELSE
      elided := part1; -- unexpected shape; leave the consonant part as-is
    END IF;

    step1_result := elided || ' + ' || struck_u || ' + ' || part2 || ' → ' || elided || ' + ' || part2;
    step2_result := elided || ' + ' || part2 || ' = ' || rec.after_form;

    UPDATE sandhi_rules SET
      changed_letter = NULL,
      rule_steps = jsonb_build_array(
        jsonb_build_object('condition', 'விதி 1', 'rule', 'உயிர்வரின் உக்குறள் மெய்விட்டு ஓடும்', 'result', step1_result),
        jsonb_build_object('condition', 'விதி 2', 'rule', 'உடல்மேல் உயிர்வந்து ஒன்றுவது இயல்பே', 'result', step2_result)
      )
    WHERE id = rec.id;

    n := n + 1;
  END LOOP;

  RAISE NOTICE '✓ Fixed % குற்றியலுகர உகர-elision rows.', n;
END $$;

-- ── Guaranteed direct fix for வேண்டு + இன், in case its mnemonic_tag isn't
--    actually set to one of the four tags above on your live DB ─────────────
UPDATE sandhi_rules SET
  mnemonic_tag = COALESCE(mnemonic_tag, 'டு று | உயிர்'),
  mnemonic_hierarchy = CASE WHEN mnemonic_hierarchy IS NULL
    THEN '["உ | உ", "உ | உயிர்", "கு | உயிர்", "டு று | உயிர்"]'::jsonb
    ELSE mnemonic_hierarchy END,
  changed_letter = NULL,
  rule_steps = '[
    {"condition": "விதி 1", "rule": "உயிர்வரின் உக்குறள் மெய்விட்டு ஓடும்", "result": "வேண்ட் + உ̶ + இன் → வேண்ட் + இன்"},
    {"condition": "விதி 2", "rule": "உடல்மேல் உயிர்வந்து ஒன்றுவது இயல்பே", "result": "வேண்ட் + இன் = வேண்டின்"}
  ]'::jsonb
WHERE before_form = 'வேண்டு + இன்' AND after_form = 'வேண்டின்';

-- ── Verify ─────────────────────────────────────────────────────────────────
SELECT before_form, after_form, mnemonic_tag, changed_letter, rule_steps
FROM sandhi_rules
WHERE mnemonic_tag IN ('உ | உயிர்', 'கு சு து பு | உயிர்', 'டு று | உயிர்', 'மு | உயிர்')
   OR (before_form = 'வேண்டு + இன்');
